### PR TITLE
Add overlay

### PR DESCRIPTION
**Pull request by pan-mroku**
I wanted to print the stack in EDMC Overlay so I wrote a few lines.

I used [edmcoverlay2 for linux](https://github.com/sersorrel/edmcoverlay2) but it should be compatible with the [EDMCOverlay](https://github.com/inorton/EDMCOverlay).

If the code will not be able to import edmcoverlay (low case for compatibility with [EDR](https://github.com/lekeno/edr)) the overlay object will not be updating so it should not break even if user checks "use overlay" in the settings when not having an overlay installed.

Could you please take a look?

### CODE REVIEW

**Comment by CMDR-WDX** [comment]
Hey. Thank you for your pull request!

I haven't really considered integrations with other plugins yet. I think it would be a better approach to extract the integration-specific code into a separate module. Say for example for the edmcoverlay integration there would be an extra module with just the Integration's code.

I am thinking about something like 
``` 
massacre
  |—integrations
  |       |— edmcoverlay
  |       |        |— main.py
  |       |        |— settings.py
  |       |         ˘— ...
  |        ˘ — other integration ...
   ˘— ...
``` 

with the idea being that `main.py` has a way to check if said plugin exists, eg:
```py
__exists: Optional[bool] = None

def exists():
    global __exists
    if __exists is None:
        try:
            import edmcoverlay
            __exists = True
        except:
            __exists = False
    return __exists
```

if this would return true, the Configuration would for example call a method in settings.py to build the relevant section of the UI and notify the module when the user has made their changes.

Would something like this work for you? If so I could make the relevant changes to the codebase and get back to you :)

**Comment by pan-mroku** [comment]
> the Configuration would for example call a method in settings.py to build the relevant section of the UI and notify the module when the user has made their changes.

You mean the UI in the main EDMC screen? Because the overlay integration does not create any. All the printing to overlay is governed inside it and doesn't touch the main window.

> with the idea being that main.py has a way to check if said plugin exists

I agree that my way of checking it is rather hacky. The problem is, if the module does not exist in PYTHONPATH, we cannot import it outside a try. So even with your proposal, we cannot simply `import edmcoverlay` at the top of overlay file. The moment you `import integrations.edmcoverlay.overlay`(?) you'll get an exception, even if you put calls to it behind `if integrations.edmcoverlay.main.exists():`.

>edmcoverlay integration there would be an extra module with just the Integration's code

For overlay, we are not creating tk widgets. We need simple strings. And from my perspective a little bit different ones. If you want to do this that way, we would have to have one module that will output the mission stack in some structure and then basically `tk_integration` and `overlay_integration` that will transform it into widgets and calls respectively.

Do you have an "integration ready" branch where we could evaluate this idea in practice?

Do you have other integrations in mind and this is a simple feature that can be used to implement the architecture? In my personal opinion you are overcomplicating this a little and we could use that energy to implement kill tracking. But I absolutely don't intend, nor am I in position to, tell you how to organize your own project. :)
It's your call :)

**Comment by CMDR-WDX** [comment]
Im working on some coupling code for integrations. I will push it later today

**Comment by CMDR-WDX** [comment]
@pan-mroku I do not have the Overlay installed. Could you please see if it still works with these new changes?

**Comment by pan-mroku** [comment]
I admit, I did not analyze your code profusely. But it seems that you had a typo and in order to understand what's going on I added two lines of log. Please take a look and decide if these should stay.

Also, it seems that plugin was throwing an error on civil war missions. Second commit addresses that.

**Comment by CMDR-WDX** [comment]
Thank you. I will create a new release this weekend :)

**Pull request merged**
